# Horse Racing Prediction by Deep Learning

This AI Horse racing prediction is using a 3-layer Neural Network to predict the finishing position of each horse in a race. The data used to train this model is obtained from the Hong Kong Jockey Club (HKJC). The model is built and trained by Tensorflow. Supervised learning is used in this project to classify the expected finishing position of the horses.

<H2> Part 1: Data Input and Preprocessing </H2>

In this part of the program, we will import the data obtained from the HKJC. First of all, the following features were selected based on my past horse picking experience, namely:

- position: The starting position of the horse. If the position is "1", it indicates the closest position to the hurdle and should be benficial in non-straight race courses.

- load: This is the loading of the horse in pounds. Maximum is 133.

- ON odds: This is the overnight odds of the horse provided by the HKJC.

- odds: This is the odds of the horse 15 min before the race.

- class: This is the class of the case. It is common to all horses in a race except special races.

- num horses: This is the number of horses participated in the race.


In [1]:
#Loading the data and preprocessing it.

import pandas as pd
import tensorflow as tf
#tf.__version__

PATH_TRAINING_DATA = 'training_data/horse_data_train_test.csv'

dataset = pd.read_csv(PATH_TRAINING_DATA)
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0, shuffle=False)


In [2]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train) #use "fit_transform" for training data
X_test = sc.transform(X_test)       #use "transform" for testing data

y_train = tf.keras.utils.to_categorical((y_train-1), 14)
y_test = tf.keras.utils.to_categorical((y_test-1), 14)

print(y_train)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


<H2> Part 2: Building the Model </H2>

We will construct a basic 3-layer model: one input layer, one output layer and one hidden layer.
I have tried relu and sigmoid as the activation, and found that sigmoid seems to be a better choice for this project.


In [3]:
#create a new model
def build_model():

    # Initializing the ANN
    model = tf.keras.models.Sequential()

    # Adding the input layer and the first layer
    # We have six features now, and one bias term, so the input layer has a size of 6+1
    #model.add(tf.keras.layers.Dense(units=6, activation='sigmoid'))
    model.add(tf.keras.layers.Dense(units=7, activation='sigmoid'))
    #model.add(tf.keras.layers.Dense(units=7, activation='relu'))

    # Adding the input layer and the hidden layer
    # We set the size of the hidden layer to be the mean of input and output later, i.e. 10
    #model.add(tf.keras.layers.Dense(units=5, activation='sigmoid')) 
    #model.add(tf.keras.layers.Dense(units=6, activation='sigmoid')) 
    #model.add(tf.keras.layers.Dense(units=10, activation='sigmoid')) 
    #model.add(tf.keras.layers.Dense(units=10, activation='relu')) 
    model.add(tf.keras.layers.Dense(units=6, activation='sigmoid')) 

    # Adding a drop out layer
    #model.add(tf.keras.layers.Dropout(0.2))
    #model.add(tf.keras.layers.Dropout(0.3))
    model.add(tf.keras.layers.Dropout(0.35277))

    #model.add(tf.keras.layers.Dense(units=6, activation='sigmoid')) 
    #model.add(tf.keras.layers.Dropout(0.2))

    # Adding the output layer
    # We have 14 outputs, so the output later has a size of 14
    model.add(tf.keras.layers.Dense(units=14, activation='softmax'))

    # Compiling the model
    #opt = tf.keras.optimizers.Adam(learning_rate=0.03) 
    opt = tf.keras.optimizers.Adam(learning_rate=0.01)
    model.compile(loss = 'categorical_crossentropy', optimizer = opt, metrics = ['accuracy'])
    
    return model

model = build_model() 

<H2> Part 3a: [Optional] Training and saving a new Model </H2>

In this section, we would either traing the model from scratch or just load a pre-trained model that is shipped with this Jupyter notebook.

- If the training data has been changed or the model has been renewed, go to train a new model in code cell 3a)
- If you want to save some time, just skip cell 3a) and load a pre-trained model in code cell 3b)


In [5]:
#This is code cell 3a) that trains a model from scratch and then saves it. Please note that it takes hours to train!

import tensorflow as tf
import datetime, os

%load_ext tensorboard
#%reload_ext tensorboard

logdir = os.path.join("logs", datetime.datetime.now().strftime("%Y%m%d-%H%M%S"))
tensorboard_callback = tf.keras.callbacks.TensorBoard(logdir, histogram_freq=1)

print("rows in X_train = " + str(X_train.shape[0]) )
print("rows in y_train = " + str(y_train.shape[0]) )

print("Training model...")
model.fit(x=X_train, 
          y=y_train, 
          batch_size = 14, 
          epochs = 5000, #10, #10000, #30000 #50000 #20000
          validation_data=(X_test, y_test), 
          callbacks=[tensorboard_callback])

# save the model for later use
print("Saving model...")
model.save('saved_model/my_model')

print("Model saved!")

rows in X_train = 491
rows in y_train = 491
Training model...
Epoch 1/5000
36/36 [==============================] - 2s 24ms/step - loss: 2.6962 - accuracy: 0.0754 - val_loss: 2.6211 - val_accuracy: 0.0976
Epoch 2/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.6560 - accuracy: 0.0407 - val_loss: 2.6185 - val_accuracy: 0.0976
Epoch 3/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.6248 - accuracy: 0.0896 - val_loss: 2.6014 - val_accuracy: 0.0976
Epoch 4/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.6148 - accuracy: 0.0916 - val_loss: 2.5809 - val_accuracy: 0.1138
Epoch 5/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.5858 - accuracy: 0.1161 - val_loss: 2.5402 - val_accuracy: 0.1301
Epoch 6/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.5499 - accuracy: 0.1324 - val_loss: 2.5034 - val_accuracy: 0.1301
Epoch 7/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.5066 - ac

Epoch 58/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.3253 - accuracy: 0.1609 - val_loss: 2.2963 - val_accuracy: 0.1707
Epoch 59/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.2874 - accuracy: 0.1711 - val_loss: 2.2967 - val_accuracy: 0.1545
Epoch 60/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.2941 - accuracy: 0.1548 - val_loss: 2.3105 - val_accuracy: 0.1789
Epoch 61/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.3307 - accuracy: 0.1731 - val_loss: 2.2974 - val_accuracy: 0.1463
Epoch 62/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.3334 - accuracy: 0.1507 - val_loss: 2.3029 - val_accuracy: 0.1789
Epoch 63/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.3299 - accuracy: 0.1711 - val_loss: 2.3077 - val_accuracy: 0.1870
Epoch 64/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.3120 - accuracy: 0.1853 - val_loss: 2.3080 - val_accuracy: 0.1870

Epoch 172/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.2551 - accuracy: 0.1935 - val_loss: 2.2916 - val_accuracy: 0.1789
Epoch 173/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.2521 - accuracy: 0.2016 - val_loss: 2.2880 - val_accuracy: 0.1707
Epoch 174/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.2592 - accuracy: 0.1670 - val_loss: 2.2946 - val_accuracy: 0.1951
Epoch 175/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.2559 - accuracy: 0.1752 - val_loss: 2.2902 - val_accuracy: 0.1951
Epoch 176/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.2788 - accuracy: 0.1690 - val_loss: 2.2900 - val_accuracy: 0.1951
Epoch 177/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.2257 - accuracy: 0.1935 - val_loss: 2.3030 - val_accuracy: 0.2114
Epoch 178/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.2497 - accuracy: 0.1874 - val_loss: 2.2852 - val_accuracy:

Epoch 229/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.2465 - accuracy: 0.1996 - val_loss: 2.2732 - val_accuracy: 0.1951
Epoch 230/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.2075 - accuracy: 0.1813 - val_loss: 2.2786 - val_accuracy: 0.1951
Epoch 231/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.2398 - accuracy: 0.1914 - val_loss: 2.2797 - val_accuracy: 0.1951
Epoch 232/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.2420 - accuracy: 0.1894 - val_loss: 2.2661 - val_accuracy: 0.2033
Epoch 233/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.2188 - accuracy: 0.2098 - val_loss: 2.2690 - val_accuracy: 0.2114
Epoch 234/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.2378 - accuracy: 0.1976 - val_loss: 2.2784 - val_accuracy: 0.1870
Epoch 235/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.2275 - accuracy: 0.1996 - val_loss: 2.2828 - val_accuracy:

Epoch 342/5000
36/36 [==============================] - 0s 6ms/step - loss: 2.1649 - accuracy: 0.2179 - val_loss: 2.2793 - val_accuracy: 0.1951
Epoch 343/5000
36/36 [==============================] - 0s 5ms/step - loss: 2.1850 - accuracy: 0.2301 - val_loss: 2.2866 - val_accuracy: 0.1870
Epoch 344/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.1839 - accuracy: 0.1935 - val_loss: 2.2844 - val_accuracy: 0.2114
Epoch 345/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.1830 - accuracy: 0.2301 - val_loss: 2.2891 - val_accuracy: 0.1951
Epoch 346/5000
36/36 [==============================] - 0s 5ms/step - loss: 2.2167 - accuracy: 0.2016 - val_loss: 2.2864 - val_accuracy: 0.1707
Epoch 347/5000
36/36 [==============================] - 0s 5ms/step - loss: 2.1742 - accuracy: 0.2179 - val_loss: 2.2894 - val_accuracy: 0.1951
Epoch 348/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.1845 - accuracy: 0.2118 - val_loss: 2.2878 - val_accuracy:

Epoch 399/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.1594 - accuracy: 0.2424 - val_loss: 2.2844 - val_accuracy: 0.2033
Epoch 400/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.1705 - accuracy: 0.1996 - val_loss: 2.2787 - val_accuracy: 0.1626
Epoch 401/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.1457 - accuracy: 0.2200 - val_loss: 2.2810 - val_accuracy: 0.1707
Epoch 402/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.1326 - accuracy: 0.2505 - val_loss: 2.2881 - val_accuracy: 0.1707
Epoch 403/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.1670 - accuracy: 0.2281 - val_loss: 2.2885 - val_accuracy: 0.2033
Epoch 404/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.1594 - accuracy: 0.2261 - val_loss: 2.2901 - val_accuracy: 0.1951
Epoch 405/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.1938 - accuracy: 0.2220 - val_loss: 2.2893 - val_accuracy:

Epoch 456/5000
36/36 [==============================] - 0s 5ms/step - loss: 2.1552 - accuracy: 0.2098 - val_loss: 2.2964 - val_accuracy: 0.2033
Epoch 457/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.1352 - accuracy: 0.2322 - val_loss: 2.2918 - val_accuracy: 0.1870
Epoch 458/5000
36/36 [==============================] - 0s 5ms/step - loss: 2.1348 - accuracy: 0.2240 - val_loss: 2.2904 - val_accuracy: 0.1626
Epoch 459/5000
36/36 [==============================] - 0s 5ms/step - loss: 2.1578 - accuracy: 0.2240 - val_loss: 2.2874 - val_accuracy: 0.1463
Epoch 460/5000
36/36 [==============================] - 0s 5ms/step - loss: 2.1017 - accuracy: 0.2403 - val_loss: 2.2873 - val_accuracy: 0.1626
Epoch 461/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.1456 - accuracy: 0.2301 - val_loss: 2.2900 - val_accuracy: 0.1789
Epoch 462/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.1222 - accuracy: 0.2464 - val_loss: 2.2794 - val_accuracy:

Epoch 569/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.1217 - accuracy: 0.2261 - val_loss: 2.3079 - val_accuracy: 0.1707
Epoch 570/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.1251 - accuracy: 0.2342 - val_loss: 2.2932 - val_accuracy: 0.1870
Epoch 571/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.1247 - accuracy: 0.2342 - val_loss: 2.2936 - val_accuracy: 0.1870
Epoch 572/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0978 - accuracy: 0.2464 - val_loss: 2.3019 - val_accuracy: 0.2033
Epoch 573/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.1352 - accuracy: 0.2383 - val_loss: 2.2931 - val_accuracy: 0.1789
Epoch 574/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.1157 - accuracy: 0.2566 - val_loss: 2.3096 - val_accuracy: 0.1870
Epoch 575/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.1649 - accuracy: 0.2098 - val_loss: 2.3018 - val_accuracy:

Epoch 626/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.1294 - accuracy: 0.2281 - val_loss: 2.3064 - val_accuracy: 0.1545
Epoch 627/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.1450 - accuracy: 0.2281 - val_loss: 2.3068 - val_accuracy: 0.1789
Epoch 628/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0799 - accuracy: 0.2505 - val_loss: 2.3047 - val_accuracy: 0.1545
Epoch 629/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.1234 - accuracy: 0.2444 - val_loss: 2.3082 - val_accuracy: 0.1707
Epoch 630/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.1352 - accuracy: 0.2444 - val_loss: 2.3081 - val_accuracy: 0.1870
Epoch 631/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.1403 - accuracy: 0.2342 - val_loss: 2.3084 - val_accuracy: 0.1707
Epoch 632/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.1228 - accuracy: 0.2383 - val_loss: 2.3056 - val_accuracy:

Epoch 683/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.1046 - accuracy: 0.2424 - val_loss: 2.3082 - val_accuracy: 0.1545
Epoch 684/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.1013 - accuracy: 0.2424 - val_loss: 2.3104 - val_accuracy: 0.1626
Epoch 685/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0880 - accuracy: 0.2566 - val_loss: 2.3280 - val_accuracy: 0.1789
Epoch 686/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.1008 - accuracy: 0.2322 - val_loss: 2.3266 - val_accuracy: 0.1626
Epoch 687/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.1259 - accuracy: 0.2261 - val_loss: 2.3128 - val_accuracy: 0.1707
Epoch 688/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.1359 - accuracy: 0.2281 - val_loss: 2.3005 - val_accuracy: 0.1626
Epoch 689/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.1324 - accuracy: 0.2383 - val_loss: 2.3017 - val_accuracy:

Epoch 740/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.1272 - accuracy: 0.2505 - val_loss: 2.3218 - val_accuracy: 0.1789
Epoch 741/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.1014 - accuracy: 0.2464 - val_loss: 2.3140 - val_accuracy: 0.1870
Epoch 742/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0948 - accuracy: 0.2525 - val_loss: 2.3153 - val_accuracy: 0.1707
Epoch 743/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.1383 - accuracy: 0.2383 - val_loss: 2.3161 - val_accuracy: 0.1707
Epoch 744/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.1251 - accuracy: 0.2403 - val_loss: 2.3127 - val_accuracy: 0.1870
Epoch 745/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.1673 - accuracy: 0.2261 - val_loss: 2.3052 - val_accuracy: 0.1707
Epoch 746/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.1127 - accuracy: 0.2566 - val_loss: 2.3083 - val_accuracy:

Epoch 797/5000
36/36 [==============================] - 0s 7ms/step - loss: 2.1101 - accuracy: 0.2403 - val_loss: 2.3322 - val_accuracy: 0.1789
Epoch 798/5000
36/36 [==============================] - 0s 6ms/step - loss: 2.1137 - accuracy: 0.2403 - val_loss: 2.3168 - val_accuracy: 0.1707
Epoch 799/5000
36/36 [==============================] - 0s 6ms/step - loss: 2.0846 - accuracy: 0.2729 - val_loss: 2.3294 - val_accuracy: 0.1707
Epoch 800/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.1234 - accuracy: 0.2342 - val_loss: 2.3324 - val_accuracy: 0.1789
Epoch 801/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.1315 - accuracy: 0.2301 - val_loss: 2.3263 - val_accuracy: 0.1707
Epoch 802/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.1406 - accuracy: 0.2342 - val_loss: 2.3251 - val_accuracy: 0.1707
Epoch 803/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.1317 - accuracy: 0.2464 - val_loss: 2.3170 - val_accuracy:

Epoch 854/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0994 - accuracy: 0.2648 - val_loss: 2.3373 - val_accuracy: 0.1789
Epoch 855/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.1162 - accuracy: 0.2403 - val_loss: 2.3352 - val_accuracy: 0.1545
Epoch 856/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.1023 - accuracy: 0.2424 - val_loss: 2.3420 - val_accuracy: 0.1789
Epoch 857/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.1098 - accuracy: 0.2566 - val_loss: 2.3356 - val_accuracy: 0.1626
Epoch 858/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.1041 - accuracy: 0.2566 - val_loss: 2.3220 - val_accuracy: 0.1626
Epoch 859/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.1160 - accuracy: 0.2383 - val_loss: 2.3478 - val_accuracy: 0.1626
Epoch 860/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.1025 - accuracy: 0.2383 - val_loss: 2.3188 - val_accuracy:

Epoch 911/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.1188 - accuracy: 0.2444 - val_loss: 2.3517 - val_accuracy: 0.1545
Epoch 912/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0786 - accuracy: 0.2607 - val_loss: 2.3455 - val_accuracy: 0.1870
Epoch 913/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0718 - accuracy: 0.2525 - val_loss: 2.3293 - val_accuracy: 0.1707
Epoch 914/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.1134 - accuracy: 0.2383 - val_loss: 2.3489 - val_accuracy: 0.1463
Epoch 915/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.1003 - accuracy: 0.2424 - val_loss: 2.3598 - val_accuracy: 0.1951
Epoch 916/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.1396 - accuracy: 0.2424 - val_loss: 2.3194 - val_accuracy: 0.1626
Epoch 917/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.1012 - accuracy: 0.2485 - val_loss: 2.3227 - val_accuracy:

Epoch 968/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.1107 - accuracy: 0.2301 - val_loss: 2.3335 - val_accuracy: 0.1707
Epoch 969/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0972 - accuracy: 0.2342 - val_loss: 2.3314 - val_accuracy: 0.1870
Epoch 970/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.1117 - accuracy: 0.2383 - val_loss: 2.3236 - val_accuracy: 0.1789
Epoch 971/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.1036 - accuracy: 0.2464 - val_loss: 2.3395 - val_accuracy: 0.1870
Epoch 972/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0950 - accuracy: 0.2464 - val_loss: 2.3112 - val_accuracy: 0.1707
Epoch 973/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0824 - accuracy: 0.2811 - val_loss: 2.3419 - val_accuracy: 0.1707
Epoch 974/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0660 - accuracy: 0.2668 - val_loss: 2.3022 - val_accuracy:

Epoch 1025/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0933 - accuracy: 0.2546 - val_loss: 2.3258 - val_accuracy: 0.1870
Epoch 1026/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.1056 - accuracy: 0.2261 - val_loss: 2.3354 - val_accuracy: 0.1626
Epoch 1027/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.1043 - accuracy: 0.2424 - val_loss: 2.3359 - val_accuracy: 0.1870
Epoch 1028/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0991 - accuracy: 0.2485 - val_loss: 2.3465 - val_accuracy: 0.2276
Epoch 1029/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0659 - accuracy: 0.2444 - val_loss: 2.3583 - val_accuracy: 0.1951
Epoch 1030/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0937 - accuracy: 0.2525 - val_loss: 2.3335 - val_accuracy: 0.1789
Epoch 1031/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0995 - accuracy: 0.2444 - val_loss: 2.3178 - val_ac

36/36 [==============================] - 0s 3ms/step - loss: 2.1091 - accuracy: 0.2424 - val_loss: 2.3473 - val_accuracy: 0.1870
Epoch 1138/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0802 - accuracy: 0.2322 - val_loss: 2.3321 - val_accuracy: 0.1870
Epoch 1139/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0761 - accuracy: 0.2546 - val_loss: 2.3272 - val_accuracy: 0.1870
Epoch 1140/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.1194 - accuracy: 0.2220 - val_loss: 2.3422 - val_accuracy: 0.1870
Epoch 1141/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.1337 - accuracy: 0.2342 - val_loss: 2.3389 - val_accuracy: 0.1789
Epoch 1142/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0745 - accuracy: 0.2688 - val_loss: 2.3348 - val_accuracy: 0.1789
Epoch 1143/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0635 - accuracy: 0.2709 - val_loss: 2.3292 - val_accuracy: 0.1707
E

36/36 [==============================] - 0s 3ms/step - loss: 2.0839 - accuracy: 0.2546 - val_loss: 2.3694 - val_accuracy: 0.1789
Epoch 1250/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.1230 - accuracy: 0.2301 - val_loss: 2.3618 - val_accuracy: 0.1870
Epoch 1251/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0767 - accuracy: 0.2607 - val_loss: 2.3616 - val_accuracy: 0.1789
Epoch 1252/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.1114 - accuracy: 0.2200 - val_loss: 2.3413 - val_accuracy: 0.1951
Epoch 1253/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0967 - accuracy: 0.2363 - val_loss: 2.3862 - val_accuracy: 0.1545
Epoch 1254/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0972 - accuracy: 0.2505 - val_loss: 2.3656 - val_accuracy: 0.1545
Epoch 1255/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0738 - accuracy: 0.2424 - val_loss: 2.3549 - val_accuracy: 0.1463
E

36/36 [==============================] - 0s 3ms/step - loss: 2.0763 - accuracy: 0.2525 - val_loss: 2.3779 - val_accuracy: 0.1707
Epoch 1362/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0465 - accuracy: 0.2709 - val_loss: 2.4015 - val_accuracy: 0.1789
Epoch 1363/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0909 - accuracy: 0.2505 - val_loss: 2.3992 - val_accuracy: 0.2114
Epoch 1364/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.1047 - accuracy: 0.2363 - val_loss: 2.3716 - val_accuracy: 0.2033
Epoch 1365/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0845 - accuracy: 0.2342 - val_loss: 2.4127 - val_accuracy: 0.1951
Epoch 1366/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0944 - accuracy: 0.2403 - val_loss: 2.3919 - val_accuracy: 0.2033
Epoch 1367/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.1027 - accuracy: 0.2301 - val_loss: 2.3919 - val_accuracy: 0.1870
E

36/36 [==============================] - 0s 3ms/step - loss: 2.0933 - accuracy: 0.2301 - val_loss: 2.4460 - val_accuracy: 0.1707
Epoch 1474/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.1040 - accuracy: 0.2159 - val_loss: 2.4203 - val_accuracy: 0.1707
Epoch 1475/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0638 - accuracy: 0.2301 - val_loss: 2.4504 - val_accuracy: 0.1626
Epoch 1476/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0833 - accuracy: 0.2281 - val_loss: 2.4182 - val_accuracy: 0.1870
Epoch 1477/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0929 - accuracy: 0.2301 - val_loss: 2.4306 - val_accuracy: 0.1789
Epoch 1478/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0612 - accuracy: 0.2322 - val_loss: 2.4315 - val_accuracy: 0.2195
Epoch 1479/5000
36/36 [==============================] - 0s 5ms/step - loss: 2.1087 - accuracy: 0.2403 - val_loss: 2.4461 - val_accuracy: 0.1870
E

36/36 [==============================] - 0s 4ms/step - loss: 2.0566 - accuracy: 0.2546 - val_loss: 2.4483 - val_accuracy: 0.2033
Epoch 1586/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0708 - accuracy: 0.2220 - val_loss: 2.5046 - val_accuracy: 0.1789
Epoch 1587/5000
36/36 [==============================] - 0s 5ms/step - loss: 2.0766 - accuracy: 0.2444 - val_loss: 2.4638 - val_accuracy: 0.1707
Epoch 1588/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0368 - accuracy: 0.2607 - val_loss: 2.4690 - val_accuracy: 0.1870
Epoch 1589/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0461 - accuracy: 0.2363 - val_loss: 2.5226 - val_accuracy: 0.1789
Epoch 1590/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.1247 - accuracy: 0.2301 - val_loss: 2.4881 - val_accuracy: 0.1707
Epoch 1591/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0363 - accuracy: 0.2607 - val_loss: 2.4751 - val_accuracy: 0.1707
E

36/36 [==============================] - 0s 4ms/step - loss: 2.0870 - accuracy: 0.2424 - val_loss: 2.4967 - val_accuracy: 0.1951
Epoch 1698/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0874 - accuracy: 0.2444 - val_loss: 2.5330 - val_accuracy: 0.1870
Epoch 1699/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0805 - accuracy: 0.2383 - val_loss: 2.5099 - val_accuracy: 0.1870
Epoch 1700/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0858 - accuracy: 0.2383 - val_loss: 2.5191 - val_accuracy: 0.1870
Epoch 1701/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0843 - accuracy: 0.2240 - val_loss: 2.5453 - val_accuracy: 0.1789
Epoch 1702/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0759 - accuracy: 0.2403 - val_loss: 2.5423 - val_accuracy: 0.1789
Epoch 1703/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0963 - accuracy: 0.2261 - val_loss: 2.5062 - val_accuracy: 0.1951
E

36/36 [==============================] - 0s 4ms/step - loss: 2.0639 - accuracy: 0.2444 - val_loss: 2.5863 - val_accuracy: 0.1707
Epoch 1810/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0296 - accuracy: 0.2587 - val_loss: 2.5888 - val_accuracy: 0.1789
Epoch 1811/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0874 - accuracy: 0.2383 - val_loss: 2.5293 - val_accuracy: 0.1870
Epoch 1812/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0659 - accuracy: 0.2342 - val_loss: 2.5517 - val_accuracy: 0.1789
Epoch 1813/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0694 - accuracy: 0.2505 - val_loss: 2.5678 - val_accuracy: 0.1789
Epoch 1814/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0442 - accuracy: 0.2648 - val_loss: 2.5403 - val_accuracy: 0.1789
Epoch 1815/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0732 - accuracy: 0.2383 - val_loss: 2.5555 - val_accuracy: 0.1789
E

36/36 [==============================] - 0s 4ms/step - loss: 2.0735 - accuracy: 0.2363 - val_loss: 2.5097 - val_accuracy: 0.1870
Epoch 1922/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0760 - accuracy: 0.2464 - val_loss: 2.5616 - val_accuracy: 0.1789
Epoch 1923/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0396 - accuracy: 0.2770 - val_loss: 2.5745 - val_accuracy: 0.1789
Epoch 1924/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.1034 - accuracy: 0.2240 - val_loss: 2.5330 - val_accuracy: 0.1870
Epoch 1925/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.1002 - accuracy: 0.2301 - val_loss: 2.5521 - val_accuracy: 0.1951
Epoch 1926/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0755 - accuracy: 0.2424 - val_loss: 2.5583 - val_accuracy: 0.1951
Epoch 1927/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0540 - accuracy: 0.2261 - val_loss: 2.5123 - val_accuracy: 0.2114
E

36/36 [==============================] - 0s 4ms/step - loss: 2.0633 - accuracy: 0.2485 - val_loss: 2.4795 - val_accuracy: 0.1870
Epoch 2034/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0883 - accuracy: 0.2546 - val_loss: 2.5215 - val_accuracy: 0.1951
Epoch 2035/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0689 - accuracy: 0.2546 - val_loss: 2.5736 - val_accuracy: 0.2033
Epoch 2036/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0795 - accuracy: 0.2383 - val_loss: 2.5845 - val_accuracy: 0.1951
Epoch 2037/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0617 - accuracy: 0.2464 - val_loss: 2.5417 - val_accuracy: 0.1951
Epoch 2038/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0884 - accuracy: 0.2424 - val_loss: 2.5545 - val_accuracy: 0.1870
Epoch 2039/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0396 - accuracy: 0.2485 - val_loss: 2.5104 - val_accuracy: 0.1951
E

36/36 [==============================] - 0s 3ms/step - loss: 2.0678 - accuracy: 0.2546 - val_loss: 2.5620 - val_accuracy: 0.2114
Epoch 2146/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0355 - accuracy: 0.2648 - val_loss: 2.5622 - val_accuracy: 0.1951
Epoch 2147/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0774 - accuracy: 0.2342 - val_loss: 2.4986 - val_accuracy: 0.1951
Epoch 2148/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0502 - accuracy: 0.2525 - val_loss: 2.5250 - val_accuracy: 0.1951
Epoch 2149/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0975 - accuracy: 0.2322 - val_loss: 2.4913 - val_accuracy: 0.1951
Epoch 2150/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.1088 - accuracy: 0.2220 - val_loss: 2.4970 - val_accuracy: 0.2114
Epoch 2151/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0989 - accuracy: 0.2322 - val_loss: 2.5445 - val_accuracy: 0.1870
E

36/36 [==============================] - 0s 4ms/step - loss: 2.0439 - accuracy: 0.2505 - val_loss: 2.5349 - val_accuracy: 0.1789
Epoch 2258/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0623 - accuracy: 0.2525 - val_loss: 2.5441 - val_accuracy: 0.1707
Epoch 2259/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0718 - accuracy: 0.2220 - val_loss: 2.5170 - val_accuracy: 0.1707
Epoch 2260/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0140 - accuracy: 0.2485 - val_loss: 2.5428 - val_accuracy: 0.1707
Epoch 2261/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0821 - accuracy: 0.2709 - val_loss: 2.5589 - val_accuracy: 0.1626
Epoch 2262/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0604 - accuracy: 0.2668 - val_loss: 2.5452 - val_accuracy: 0.1789
Epoch 2263/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0862 - accuracy: 0.2424 - val_loss: 2.5304 - val_accuracy: 0.1545
E

36/36 [==============================] - 0s 3ms/step - loss: 2.0628 - accuracy: 0.2424 - val_loss: 2.5191 - val_accuracy: 0.1789
Epoch 2370/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0558 - accuracy: 0.2566 - val_loss: 2.5362 - val_accuracy: 0.1789
Epoch 2371/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0712 - accuracy: 0.2525 - val_loss: 2.5946 - val_accuracy: 0.1707
Epoch 2372/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0447 - accuracy: 0.2505 - val_loss: 2.5729 - val_accuracy: 0.1870
Epoch 2373/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0740 - accuracy: 0.2525 - val_loss: 2.6045 - val_accuracy: 0.2114
Epoch 2374/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0790 - accuracy: 0.2240 - val_loss: 2.5816 - val_accuracy: 0.2114
Epoch 2375/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0755 - accuracy: 0.2342 - val_loss: 2.5869 - val_accuracy: 0.2033
E

36/36 [==============================] - 0s 4ms/step - loss: 2.0602 - accuracy: 0.2505 - val_loss: 2.5997 - val_accuracy: 0.1870
Epoch 2482/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0505 - accuracy: 0.2546 - val_loss: 2.6083 - val_accuracy: 0.1789
Epoch 2483/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0530 - accuracy: 0.2627 - val_loss: 2.6081 - val_accuracy: 0.1789
Epoch 2484/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0926 - accuracy: 0.2403 - val_loss: 2.5779 - val_accuracy: 0.1707
Epoch 2485/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0289 - accuracy: 0.2729 - val_loss: 2.6213 - val_accuracy: 0.1707
Epoch 2486/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0694 - accuracy: 0.2301 - val_loss: 2.5152 - val_accuracy: 0.1707
Epoch 2487/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0430 - accuracy: 0.2749 - val_loss: 2.5971 - val_accuracy: 0.1626
E

36/36 [==============================] - 0s 4ms/step - loss: 2.0411 - accuracy: 0.2587 - val_loss: 2.6101 - val_accuracy: 0.1545
Epoch 2594/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0849 - accuracy: 0.2240 - val_loss: 2.5827 - val_accuracy: 0.1707
Epoch 2595/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0964 - accuracy: 0.2587 - val_loss: 2.5415 - val_accuracy: 0.1707
Epoch 2596/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0547 - accuracy: 0.2587 - val_loss: 2.5270 - val_accuracy: 0.1626
Epoch 2597/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0727 - accuracy: 0.2383 - val_loss: 2.5038 - val_accuracy: 0.1626
Epoch 2598/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0486 - accuracy: 0.2403 - val_loss: 2.5626 - val_accuracy: 0.1789
Epoch 2599/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0938 - accuracy: 0.2525 - val_loss: 2.5666 - val_accuracy: 0.1789
E

36/36 [==============================] - 0s 3ms/step - loss: 2.0597 - accuracy: 0.2444 - val_loss: 2.5779 - val_accuracy: 0.1707
Epoch 2706/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0384 - accuracy: 0.2424 - val_loss: 2.6351 - val_accuracy: 0.1707
Epoch 2707/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0735 - accuracy: 0.2546 - val_loss: 2.6155 - val_accuracy: 0.1707
Epoch 2708/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0456 - accuracy: 0.2505 - val_loss: 2.6198 - val_accuracy: 0.1707
Epoch 2709/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0339 - accuracy: 0.2688 - val_loss: 2.6104 - val_accuracy: 0.1789
Epoch 2710/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0564 - accuracy: 0.2444 - val_loss: 2.6561 - val_accuracy: 0.1707
Epoch 2711/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0837 - accuracy: 0.2464 - val_loss: 2.5688 - val_accuracy: 0.1789
E

36/36 [==============================] - 0s 3ms/step - loss: 2.0506 - accuracy: 0.2566 - val_loss: 2.6547 - val_accuracy: 0.1545
Epoch 2818/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0693 - accuracy: 0.2566 - val_loss: 2.5255 - val_accuracy: 0.1707
Epoch 2819/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0870 - accuracy: 0.2607 - val_loss: 2.5912 - val_accuracy: 0.1789
Epoch 2820/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0688 - accuracy: 0.2383 - val_loss: 2.5963 - val_accuracy: 0.1626
Epoch 2821/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0316 - accuracy: 0.2566 - val_loss: 2.6412 - val_accuracy: 0.1707
Epoch 2822/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0329 - accuracy: 0.2485 - val_loss: 2.5705 - val_accuracy: 0.1707
Epoch 2823/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0476 - accuracy: 0.2546 - val_loss: 2.6530 - val_accuracy: 0.1707
E

36/36 [==============================] - 0s 3ms/step - loss: 2.0580 - accuracy: 0.2668 - val_loss: 2.6640 - val_accuracy: 0.1870
Epoch 2930/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0431 - accuracy: 0.2525 - val_loss: 2.6753 - val_accuracy: 0.1707
Epoch 2931/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0615 - accuracy: 0.2464 - val_loss: 2.6315 - val_accuracy: 0.1789
Epoch 2932/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0582 - accuracy: 0.2648 - val_loss: 2.6788 - val_accuracy: 0.1870
Epoch 2933/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0423 - accuracy: 0.2485 - val_loss: 2.6675 - val_accuracy: 0.1707
Epoch 2934/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0762 - accuracy: 0.2627 - val_loss: 2.6586 - val_accuracy: 0.1707
Epoch 2935/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0609 - accuracy: 0.2505 - val_loss: 2.6810 - val_accuracy: 0.1707
E

36/36 [==============================] - 0s 3ms/step - loss: 2.0901 - accuracy: 0.2505 - val_loss: 2.6387 - val_accuracy: 0.1707
Epoch 3042/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.1054 - accuracy: 0.2648 - val_loss: 2.6727 - val_accuracy: 0.1789
Epoch 3043/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0608 - accuracy: 0.2587 - val_loss: 2.7018 - val_accuracy: 0.1707
Epoch 3044/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0583 - accuracy: 0.2627 - val_loss: 2.6138 - val_accuracy: 0.1707
Epoch 3045/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0456 - accuracy: 0.2627 - val_loss: 2.6774 - val_accuracy: 0.1626
Epoch 3046/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0526 - accuracy: 0.2668 - val_loss: 2.7124 - val_accuracy: 0.1545
Epoch 3047/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0586 - accuracy: 0.2525 - val_loss: 2.6403 - val_accuracy: 0.1626
E

36/36 [==============================] - 0s 3ms/step - loss: 2.0616 - accuracy: 0.2648 - val_loss: 2.5915 - val_accuracy: 0.1545
Epoch 3154/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0605 - accuracy: 0.2729 - val_loss: 2.6528 - val_accuracy: 0.1545
Epoch 3155/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0364 - accuracy: 0.2790 - val_loss: 2.6632 - val_accuracy: 0.1626
Epoch 3156/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0566 - accuracy: 0.2668 - val_loss: 2.6070 - val_accuracy: 0.1789
Epoch 3157/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0515 - accuracy: 0.2607 - val_loss: 2.6214 - val_accuracy: 0.1626
Epoch 3158/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0597 - accuracy: 0.2525 - val_loss: 2.6578 - val_accuracy: 0.1870
Epoch 3159/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0443 - accuracy: 0.2546 - val_loss: 2.6738 - val_accuracy: 0.1789
E

36/36 [==============================] - 0s 3ms/step - loss: 2.0586 - accuracy: 0.2668 - val_loss: 2.7035 - val_accuracy: 0.1707
Epoch 3266/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0826 - accuracy: 0.2383 - val_loss: 2.7330 - val_accuracy: 0.1707
Epoch 3267/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0599 - accuracy: 0.2587 - val_loss: 2.7339 - val_accuracy: 0.1626
Epoch 3268/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0403 - accuracy: 0.2729 - val_loss: 2.6721 - val_accuracy: 0.1707
Epoch 3269/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0433 - accuracy: 0.2607 - val_loss: 2.6699 - val_accuracy: 0.1789
Epoch 3270/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0674 - accuracy: 0.2525 - val_loss: 2.6761 - val_accuracy: 0.1870
Epoch 3271/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0102 - accuracy: 0.2627 - val_loss: 2.6608 - val_accuracy: 0.1870
E

36/36 [==============================] - 0s 3ms/step - loss: 2.0474 - accuracy: 0.2525 - val_loss: 2.7094 - val_accuracy: 0.1545
Epoch 3378/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0307 - accuracy: 0.2770 - val_loss: 2.7778 - val_accuracy: 0.1789
Epoch 3379/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0426 - accuracy: 0.2729 - val_loss: 2.7650 - val_accuracy: 0.1626
Epoch 3380/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0504 - accuracy: 0.2627 - val_loss: 2.7675 - val_accuracy: 0.1545
Epoch 3381/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0443 - accuracy: 0.2587 - val_loss: 2.7773 - val_accuracy: 0.1545
Epoch 3382/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0496 - accuracy: 0.2587 - val_loss: 2.7712 - val_accuracy: 0.1707
Epoch 3383/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0401 - accuracy: 0.2749 - val_loss: 2.7101 - val_accuracy: 0.1789
E

36/36 [==============================] - 0s 3ms/step - loss: 2.0568 - accuracy: 0.2709 - val_loss: 2.6904 - val_accuracy: 0.1951
Epoch 3490/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0398 - accuracy: 0.2648 - val_loss: 2.7531 - val_accuracy: 0.1707
Epoch 3491/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0722 - accuracy: 0.2261 - val_loss: 2.7670 - val_accuracy: 0.1870
Epoch 3492/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0749 - accuracy: 0.2403 - val_loss: 2.6720 - val_accuracy: 0.1870
Epoch 3493/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0761 - accuracy: 0.2424 - val_loss: 2.6517 - val_accuracy: 0.1545
Epoch 3494/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0567 - accuracy: 0.2444 - val_loss: 2.6994 - val_accuracy: 0.1707
Epoch 3495/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0520 - accuracy: 0.2546 - val_loss: 2.7189 - val_accuracy: 0.1545
E

36/36 [==============================] - 0s 3ms/step - loss: 2.0627 - accuracy: 0.2485 - val_loss: 2.7228 - val_accuracy: 0.1545
Epoch 3602/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0573 - accuracy: 0.2607 - val_loss: 2.7708 - val_accuracy: 0.1545
Epoch 3603/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0766 - accuracy: 0.2281 - val_loss: 2.7991 - val_accuracy: 0.1463
Epoch 3604/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0490 - accuracy: 0.2729 - val_loss: 2.7417 - val_accuracy: 0.1626
Epoch 3605/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0369 - accuracy: 0.2485 - val_loss: 2.7466 - val_accuracy: 0.1789
Epoch 3606/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0383 - accuracy: 0.2627 - val_loss: 2.7762 - val_accuracy: 0.1626
Epoch 3607/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0828 - accuracy: 0.2424 - val_loss: 2.8096 - val_accuracy: 0.1626
E

36/36 [==============================] - 0s 4ms/step - loss: 2.0797 - accuracy: 0.2525 - val_loss: 2.7417 - val_accuracy: 0.1545
Epoch 3714/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0470 - accuracy: 0.2505 - val_loss: 2.7055 - val_accuracy: 0.1951
Epoch 3715/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0626 - accuracy: 0.2546 - val_loss: 2.6791 - val_accuracy: 0.1626
Epoch 3716/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0820 - accuracy: 0.2505 - val_loss: 2.7541 - val_accuracy: 0.1626
Epoch 3717/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0527 - accuracy: 0.2403 - val_loss: 2.7632 - val_accuracy: 0.1545
Epoch 3718/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0683 - accuracy: 0.2485 - val_loss: 2.7734 - val_accuracy: 0.1545
Epoch 3719/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0542 - accuracy: 0.2566 - val_loss: 2.7542 - val_accuracy: 0.1545
E

36/36 [==============================] - 0s 4ms/step - loss: 2.0406 - accuracy: 0.2546 - val_loss: 2.8107 - val_accuracy: 0.1870
Epoch 3826/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0748 - accuracy: 0.2587 - val_loss: 2.8430 - val_accuracy: 0.1545
Epoch 3827/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0518 - accuracy: 0.2525 - val_loss: 2.8374 - val_accuracy: 0.1463
Epoch 3828/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0338 - accuracy: 0.2464 - val_loss: 2.8247 - val_accuracy: 0.1545
Epoch 3829/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0792 - accuracy: 0.2200 - val_loss: 2.7883 - val_accuracy: 0.1545
Epoch 3830/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0401 - accuracy: 0.2444 - val_loss: 2.8201 - val_accuracy: 0.1951
Epoch 3831/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0538 - accuracy: 0.2627 - val_loss: 2.8560 - val_accuracy: 0.1707
E

36/36 [==============================] - 0s 3ms/step - loss: 2.0569 - accuracy: 0.2709 - val_loss: 2.7707 - val_accuracy: 0.1707
Epoch 3938/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0383 - accuracy: 0.2770 - val_loss: 2.7738 - val_accuracy: 0.1626
Epoch 3939/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0759 - accuracy: 0.2444 - val_loss: 2.8491 - val_accuracy: 0.1626
Epoch 3940/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0241 - accuracy: 0.2546 - val_loss: 2.7698 - val_accuracy: 0.1626
Epoch 3941/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0379 - accuracy: 0.2566 - val_loss: 2.7662 - val_accuracy: 0.1870
Epoch 3942/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0350 - accuracy: 0.2607 - val_loss: 2.7957 - val_accuracy: 0.1951
Epoch 3943/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0519 - accuracy: 0.2363 - val_loss: 2.7961 - val_accuracy: 0.1870
E

36/36 [==============================] - 0s 3ms/step - loss: 2.0830 - accuracy: 0.2566 - val_loss: 2.8113 - val_accuracy: 0.1463
Epoch 4050/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0496 - accuracy: 0.2505 - val_loss: 2.7970 - val_accuracy: 0.1545
Epoch 4051/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0109 - accuracy: 0.2587 - val_loss: 2.8572 - val_accuracy: 0.1545
Epoch 4052/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0604 - accuracy: 0.2485 - val_loss: 2.7873 - val_accuracy: 0.1626
Epoch 4053/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0580 - accuracy: 0.2485 - val_loss: 2.8861 - val_accuracy: 0.1789
Epoch 4054/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0592 - accuracy: 0.2444 - val_loss: 2.8641 - val_accuracy: 0.1789
Epoch 4055/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0627 - accuracy: 0.2383 - val_loss: 2.8285 - val_accuracy: 0.1870
E

36/36 [==============================] - 0s 3ms/step - loss: 2.0676 - accuracy: 0.2464 - val_loss: 2.8988 - val_accuracy: 0.1463
Epoch 4162/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0445 - accuracy: 0.2607 - val_loss: 2.8501 - val_accuracy: 0.1545
Epoch 4163/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0569 - accuracy: 0.2505 - val_loss: 2.9112 - val_accuracy: 0.1545
Epoch 4164/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0783 - accuracy: 0.2444 - val_loss: 2.8334 - val_accuracy: 0.1707
Epoch 4165/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0745 - accuracy: 0.2688 - val_loss: 2.8783 - val_accuracy: 0.1626
Epoch 4166/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0329 - accuracy: 0.2587 - val_loss: 2.8424 - val_accuracy: 0.1707
Epoch 4167/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0610 - accuracy: 0.2587 - val_loss: 2.7990 - val_accuracy: 0.1626
E

36/36 [==============================] - 0s 3ms/step - loss: 2.0637 - accuracy: 0.2668 - val_loss: 2.9021 - val_accuracy: 0.1626
Epoch 4274/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0763 - accuracy: 0.2403 - val_loss: 2.8570 - val_accuracy: 0.1707
Epoch 4275/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0494 - accuracy: 0.2363 - val_loss: 2.8092 - val_accuracy: 0.1463
Epoch 4276/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0585 - accuracy: 0.2566 - val_loss: 2.7784 - val_accuracy: 0.1382
Epoch 4277/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0818 - accuracy: 0.2220 - val_loss: 2.8088 - val_accuracy: 0.1545
Epoch 4278/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0426 - accuracy: 0.2607 - val_loss: 2.8900 - val_accuracy: 0.1545
Epoch 4279/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0229 - accuracy: 0.2587 - val_loss: 2.8514 - val_accuracy: 0.1463
E

36/36 [==============================] - 0s 4ms/step - loss: 2.0281 - accuracy: 0.2668 - val_loss: 2.8895 - val_accuracy: 0.1382
Epoch 4386/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0354 - accuracy: 0.2424 - val_loss: 2.8927 - val_accuracy: 0.1463
Epoch 4387/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0544 - accuracy: 0.2505 - val_loss: 2.8888 - val_accuracy: 0.1545
Epoch 4388/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0601 - accuracy: 0.2363 - val_loss: 2.9616 - val_accuracy: 0.1382
Epoch 4389/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0761 - accuracy: 0.2587 - val_loss: 2.9014 - val_accuracy: 0.1545
Epoch 4390/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0602 - accuracy: 0.2485 - val_loss: 2.8952 - val_accuracy: 0.1789
Epoch 4391/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0294 - accuracy: 0.2749 - val_loss: 2.9324 - val_accuracy: 0.1870
E

36/36 [==============================] - 0s 3ms/step - loss: 2.0761 - accuracy: 0.2607 - val_loss: 2.7839 - val_accuracy: 0.1870
Epoch 4498/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0489 - accuracy: 0.2627 - val_loss: 2.8769 - val_accuracy: 0.1626
Epoch 4499/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0631 - accuracy: 0.2648 - val_loss: 2.8441 - val_accuracy: 0.1707
Epoch 4500/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0341 - accuracy: 0.2403 - val_loss: 2.8629 - val_accuracy: 0.1626
Epoch 4501/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0257 - accuracy: 0.2811 - val_loss: 2.9002 - val_accuracy: 0.1545
Epoch 4502/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0527 - accuracy: 0.2464 - val_loss: 2.9439 - val_accuracy: 0.1789
Epoch 4503/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0170 - accuracy: 0.2953 - val_loss: 2.8997 - val_accuracy: 0.1870
E

36/36 [==============================] - 0s 4ms/step - loss: 2.0728 - accuracy: 0.2525 - val_loss: 2.9065 - val_accuracy: 0.1545
Epoch 4610/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0427 - accuracy: 0.2607 - val_loss: 2.9569 - val_accuracy: 0.1463
Epoch 4611/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0004 - accuracy: 0.2933 - val_loss: 2.9970 - val_accuracy: 0.1626
Epoch 4612/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0752 - accuracy: 0.2464 - val_loss: 2.9719 - val_accuracy: 0.1626
Epoch 4613/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0442 - accuracy: 0.2363 - val_loss: 2.9222 - val_accuracy: 0.1463
Epoch 4614/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0747 - accuracy: 0.2525 - val_loss: 2.8790 - val_accuracy: 0.1545
Epoch 4615/5000
36/36 [==============================] - 0s 4ms/step - loss: 2.0736 - accuracy: 0.2444 - val_loss: 2.8621 - val_accuracy: 0.1545
E

36/36 [==============================] - 0s 3ms/step - loss: 2.0345 - accuracy: 0.2485 - val_loss: 2.9278 - val_accuracy: 0.1463
Epoch 4722/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0816 - accuracy: 0.2464 - val_loss: 2.9510 - val_accuracy: 0.1545
Epoch 4723/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0286 - accuracy: 0.2648 - val_loss: 2.8468 - val_accuracy: 0.1463
Epoch 4724/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0714 - accuracy: 0.2322 - val_loss: 2.9754 - val_accuracy: 0.1382
Epoch 4725/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0683 - accuracy: 0.2546 - val_loss: 2.9500 - val_accuracy: 0.1626
Epoch 4726/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0505 - accuracy: 0.2546 - val_loss: 2.9395 - val_accuracy: 0.1463
Epoch 4727/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0502 - accuracy: 0.2566 - val_loss: 2.9742 - val_accuracy: 0.1707
E

36/36 [==============================] - 0s 3ms/step - loss: 2.0336 - accuracy: 0.2729 - val_loss: 2.9120 - val_accuracy: 0.1463
Epoch 4834/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0246 - accuracy: 0.2587 - val_loss: 2.9931 - val_accuracy: 0.1545
Epoch 4835/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0393 - accuracy: 0.2607 - val_loss: 2.9744 - val_accuracy: 0.1382
Epoch 4836/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0637 - accuracy: 0.2648 - val_loss: 2.9412 - val_accuracy: 0.1382
Epoch 4837/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0293 - accuracy: 0.2688 - val_loss: 2.9515 - val_accuracy: 0.1382
Epoch 4838/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0641 - accuracy: 0.2505 - val_loss: 2.8892 - val_accuracy: 0.1382
Epoch 4839/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0624 - accuracy: 0.2729 - val_loss: 2.9666 - val_accuracy: 0.1545
E

36/36 [==============================] - 0s 3ms/step - loss: 2.0744 - accuracy: 0.2444 - val_loss: 2.9750 - val_accuracy: 0.1463
Epoch 4946/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0274 - accuracy: 0.2607 - val_loss: 2.9999 - val_accuracy: 0.1545
Epoch 4947/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0199 - accuracy: 0.2587 - val_loss: 3.0496 - val_accuracy: 0.1626
Epoch 4948/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0134 - accuracy: 0.2790 - val_loss: 3.0186 - val_accuracy: 0.1789
Epoch 4949/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0343 - accuracy: 0.2587 - val_loss: 3.0303 - val_accuracy: 0.1463
Epoch 4950/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0417 - accuracy: 0.2546 - val_loss: 2.9374 - val_accuracy: 0.1545
Epoch 4951/5000
36/36 [==============================] - 0s 3ms/step - loss: 2.0539 - accuracy: 0.2627 - val_loss: 3.0207 - val_accuracy: 0.1707
E

<H2> Part 3b: Loading a pre-trained Model </H2>

If you have ever run cell 3a), you will load the model that you have trained. Otherwise, you will load a pre-trained model that is shipped with this Jupyter notebook.

In [4]:
#This is code cell 3b) that loads a pre-trained model. 

model = tf.keras.models.load_model('saved_model/my_model')

print("model is loaded")

model is loaded


<H2>Part 3c: Model Summary</H2>
    
Let's take a look on the model:

In [5]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 7)                 49        
_________________________________________________________________
dense_1 (Dense)              (None, 6)                 48        
_________________________________________________________________
dropout (Dropout)            (None, 6)                 0         
_________________________________________________________________
dense_2 (Dense)              (None, 14)                98        
Total params: 195
Trainable params: 195
Non-trainable params: 0
_________________________________________________________________


<H2> Part 4: Evaluation </H2>

This part calculates the confusion matrix and accuracy_score of the model.

In [6]:
# Restore the weights
import numpy as np
import pandas as pd

dataset = pd.read_csv('training_data/horse_data_train_test.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


import tensorflow as tf
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Predicting the Test set results
y_pred = model.predict( X_test )  #y_pred = new_model.predict( sc.fit_transform(X_test) ) 
y_pred = np.argmax(y_pred, axis = 1)

In [7]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, (y_pred+1))
print("cm=", cm)
print("accuracy_score=", accuracy_score(y_test, (y_pred+1)))

cm= [[0 9 2 0 0 0 1 0 0 0 0 0 0 0]
 [1 5 1 0 1 0 0 1 0 0 0 0 0 0]
 [0 5 1 0 1 0 0 0 0 0 0 0 0 0]
 [1 1 2 0 1 0 3 0 0 0 0 0 0 0]
 [0 1 0 0 5 0 1 2 0 0 0 0 0 1]
 [1 3 0 0 1 0 2 0 0 0 0 0 0 0]
 [0 5 0 0 2 0 3 2 0 0 0 0 0 0]
 [0 4 0 0 2 0 0 1 1 0 0 1 0 0]
 [2 1 0 0 2 0 1 1 1 0 0 0 0 1]
 [0 0 1 0 4 0 0 3 0 1 0 1 0 0]
 [0 0 1 0 2 0 0 1 0 0 1 2 2 0]
 [0 0 0 0 2 0 2 1 0 1 1 1 2 0]
 [0 0 0 0 0 0 0 0 0 0 0 2 4 1]
 [0 0 0 0 0 0 1 0 0 0 0 0 1 7]]
accuracy_score= 0.234375


<H2> Part 5: [Optional] Visualization of the model by Tensorboard </H2>

***Note:*** Run this section only if you have run Part3a.

By making use of the powerful visual tools given by Tensorboard, we can tune the hyper parameters of the model and visualize the results easily. If the epoch_accuracy is increasing steadily with epoch for the validation set, we could be confident that the model is on track. 

If we are not satisfy with the performaces shown in the Tensorboard, we can go back to refine the data processing, model building and hyper parameters and check on Tensorboard again iteratively.

In [10]:
print("Calling tensorboard...")

#import datetime, os
#%load_ext tensorboard
#logdir = os.path.join("logs", datetime.datetime.now().strftime("%Y%m%d-%H%M%S"))

%tensorboard --logdir logs --port=6008 #use a different port if tensorboard fails to load!


Calling tensorboard...


Reusing TensorBoard on port 6008 (pid 8956), started 5 days, 5:23:31 ago. (Use '!kill 8956' to kill it.)

<H2> Part 6: Prediction Checking </H2>

In this section, we will try to predict the results of a race on 2021/09/22, and see how accurate the model is by comparing the rediction witht the real results.
 

In [8]:
#This is the csv containing the data of a new race:

#CURRENT_RACE_DATA = 'new_data/horse_data_20210926_race8.csv'
#CURRENT_RACE_DATA = 'new_data/horse_data_20210926_race3.csv'
#CURRENT_RACE_DATA = 'new_data/horse_data_20210926_race10.csv'
#CURRENT_RACE_DATA = 'new_data/horse_data_20211001_race2.csv'
#CURRENT_RACE_DATA = 'new_data/horse_data_20211001_race3.csv'
#CURRENT_RACE_DATA = 'new_data/horse_data_20211001_race7.csv'
#CURRENT_RACE_DATA = 'new_data/horse_data_20211001_race9.csv'
#CURRENT_RACE_DATA = 'new_data/horse_data_20211006_race2.csv'
#CURRENT_RACE_DATA = 'new_data/horse_data_20211010_race2.csv'
#CURRENT_RACE_DATA = 'new_data/horse_data_20211017_race6.csv'
#CURRENT_RACE_DATA = 'new_data/horse_data_20211017_race8.csv'
#CURRENT_RACE_DATA = 'new_data/horse_data_20211020_race3.csv'
CURRENT_RACE_DATA = 'new_data/horse_data_20211020_race5.csv'

#CURRENT_RACE_DATA = 'new_data/horse_data_20210922_race3.csv'
REAL_FINISHING_POSITIONS = '[ 1  6  4  2 12 10  8  3  7  5 11  9 13 14]'

In [9]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

PATH_TRAINING_DATA = 'training_data/horse_data_train_test.csv'

#training data
dataset = pd.read_csv(PATH_TRAINING_DATA)
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0, shuffle=False)

sc = StandardScaler()
X_train = sc.fit_transform(X_train)

#live data
dataset = pd.read_csv(CURRENT_RACE_DATA)
X_live = dataset.iloc[:, :-1].values

#use "transform" for live data
X_live = sc.transform(X_live)

#loading pretrained model
model = tf.keras.models.load_model('saved_model/my_model')

# Predicting the Test set results
y_pred = model.predict(X_live)  

# Predicting the finishing position
y_pred_finishing = np.argmax(y_pred, axis = 1) 
print("Expected finishing positions=", y_pred_finishing+1)

print("The real finishing positions= " + REAL_FINISHING_POSITIONS)


Expected finishing positions= [5 2 5 8 8 2 2 1 5 2 5 5]
The real finishing positions= [ 1  6  4  2 12 10  8  3  7  5 11  9 13 14]


For prediction on your own, you need to create a new csv file that contains the data of a new race in the folder new_data, then run the preditction.